import { Card, CardHeader, CardTitle, CardContent, CardFooter } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { useNavigate, useParams } from "react-router-dom";
import { useEffect } from "react";
import { supabase } from "@/lib/supabase";

declare const Razorpay: any;

const plans = [
    {
        name: "Free",
        price: "$0",
        priceInPaise: 0,
        features: [
            "View overall score",
            "Partial AI report",
            "Limited to 3 checks per day",
        ],
        cta: "Current Plan",
        disabled: true,
    },
    {
        name: "Standard",
        price: "$9.99/month",
        priceInPaise: 999,
        features: [
            "Full AI report",
            "5 checks per day",
            "Valid for 1 month",
            "Email support",
        ],
        cta: "Choose Plan",
        popular: true,
    },
    {
        name: "Premium",
        price: "$29.99/month",
        priceInPaise: 2999,
        features: [
            "Full AI report",
            "Unlimited checks",
            "Priority email support",
            "Access to new features",
        ],
        cta: "Choose Plan",
    },
];

export default function Paywall() {
    const navigate = useNavigate();
    const { taskId } = useParams();

    // Fetch user's profile to check for admin status
    useEffect(() => {
        const checkAdminStatus = async () => {
            const { data: { user } } = await supabase.auth.getUser();
            if (!user) {
                navigate("/login");
                return;
            }

            // Assuming is_admin is available directly on the user object or via user_metadata/app_metadata
            // You might need to adjust this based on how you store admin status in Supabase auth.users table
            if (user.user_metadata?.is_admin || user.app_metadata?.is_admin) {
                navigate(`/view-result/${taskId}`);
                return;
            }
        };
        checkAdminStatus();
    }, [navigate, taskId]);

    const handleChoosePlan = async (plan: typeof plans[0]) => {
        if (plan.name === "Free") return;

        const { data: { user } } = await supabase.auth.getUser();
        if (!user) {
            navigate("/login");
            return;
        }

        const options = {
            key: "rzp_test_your_key_here", // Replace with your Razorpay Key ID
            amount: plan.priceInPaise * 100, // amount in the smallest currency unit
            currency: "INR",
            name: "CodeSmart",
            description: `Subscription for ${plan.name} plan`,
            order_id: "", // This will be generated by your backend
            handler: async function (response: any) {
                // In a real application, you would send this response to your backend for verification
                console.log(response);

                // Simulate successful payment and update subscription
                const { error } = await supabase
                    .from("profiles")
                    .update({ subscription_status: "active" })
                    .eq("id", user.id);

                if (error) {
                    console.error("Error updating subscription:", error);
                } else {
                    navigate(`/view-result/${taskId}`);
                }
            },
            prefill: {
                name: user.user_metadata.username || "",
                email: user.email,
                contact: "",
            },
            notes: {
                address: "CodeSmart Corporate Office",
            },
            theme: {
                color: "#3399cc",
            },
        };

        // In a real app, you would create an order on your backend and get the order_id
        // For this simulation, we will proceed without an order_id
        const rzp = new Razorpay(options);
        rzp.open();
    };

    return (
        <div className="flex flex-col min-h-screen">
            <main className="flex-1 p-4 md:p-8">
                <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-3">
                    {plans.map((plan) => (
                        <Card
                            key={plan.name}
                            className={`flex flex-col ${plan.popular ? 'border-purple-500 dark:border-purple-400 border-2' : ''}`}
                        >
                            {plan.popular && (
                                <div className="text-sm font-bold text-center text-primary-foreground bg-purple-500 dark:bg-purple-400 p-1 rounded-t-lg">
                                    Most Popular
                                </div>
                            )}
                            <CardHeader>
                                <CardTitle className="text-2xl font-bold text-foreground">{plan.name}</CardTitle>
                                <p className="text-4xl font-bold text-foreground">{plan.price}</p>
                            </CardHeader>
                            <CardContent className="flex-1">
                                <ul className="space-y-4">
                                    {plan.features.map((feature) => (
                                        <li key={feature} className="flex items-center">
                                            <svg
                                                className="w-5 h-5 mr-3 text-green-500 dark:text-green-400"
                                                fill="none"
                                                stroke="currentColor"
                                                viewBox="0 0 24 24"
                                                xmlns="http://www.w3.org/2000/svg"
                                            >
                                                <path
                                                    strokeLinecap="round"
                                                    strokeLinejoin="round"
                                                    strokeWidth={2}
                                                    d="M5 13l4 4L19 7"
                                                />
                                            </svg>
                                            <span className="text-muted-foreground">{feature}</span>
                                        </li>
                                    ))}
                                </ul>
                            </CardContent>
                            <CardFooter>
                                <Button
                                    className={`w-full text-lg py-3 ${plan.popular ? 'bg-purple-500 dark:bg-purple-400 hover:bg-purple-600 dark:hover:bg-purple-500' : 'bg-primary hover:bg-primary/90'}`}
                                    disabled={plan.disabled}
                                    onClick={() => handleChoosePlan(plan)}
                                >
                                    {plan.cta}
                                </Button>
                            </CardFooter>
                        </Card>
                    ))}
                </div>
            </main>
        </div>
    );
}